# Generated by Django 2.2.1 on 2019-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='short_link',
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='title',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
